// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: theme_packs.sql

package sqlc

import (
	"context"
)

const createThemePack = `-- name: CreateThemePack :exec
INSERT INTO theme_packs (theme_id, name, version, author, description, schema_version, raw_json)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateThemePackParams struct {
	ThemeID       string
	Name          string
	Version       string
	Author        string
	Description   string
	SchemaVersion int64
	RawJson       string
}

func (q *Queries) CreateThemePack(ctx context.Context, arg CreateThemePackParams) error {
	_, err := q.db.ExecContext(ctx, createThemePack,
		arg.ThemeID,
		arg.Name,
		arg.Version,
		arg.Author,
		arg.Description,
		arg.SchemaVersion,
		arg.RawJson,
	)
	return err
}

const deleteThemePack = `-- name: DeleteThemePack :execrows
DELETE FROM theme_packs WHERE theme_id = ?
`

func (q *Queries) DeleteThemePack(ctx context.Context, themeID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteThemePack, themeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getThemePackByThemeID = `-- name: GetThemePackByThemeID :one
SELECT id, theme_id, name, version, author, description, schema_version, raw_json, created_at, updated_at
FROM theme_packs WHERE theme_id = ?
`

func (q *Queries) GetThemePackByThemeID(ctx context.Context, themeID string) (ThemePack, error) {
	row := q.db.QueryRowContext(ctx, getThemePackByThemeID, themeID)
	var i ThemePack
	err := row.Scan(
		&i.ID,
		&i.ThemeID,
		&i.Name,
		&i.Version,
		&i.Author,
		&i.Description,
		&i.SchemaVersion,
		&i.RawJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listThemePacks = `-- name: ListThemePacks :many
SELECT id, theme_id, name, version, author, description, schema_version, raw_json, created_at, updated_at
FROM theme_packs ORDER BY created_at DESC
`

func (q *Queries) ListThemePacks(ctx context.Context) ([]ThemePack, error) {
	rows, err := q.db.QueryContext(ctx, listThemePacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThemePack{}
	for rows.Next() {
		var i ThemePack
		if err := rows.Scan(
			&i.ID,
			&i.ThemeID,
			&i.Name,
			&i.Version,
			&i.Author,
			&i.Description,
			&i.SchemaVersion,
			&i.RawJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThemePack = `-- name: UpdateThemePack :exec
UPDATE theme_packs
SET name = ?, version = ?, author = ?, description = ?, schema_version = ?, raw_json = ?
WHERE theme_id = ?
`

type UpdateThemePackParams struct {
	Name          string
	Version       string
	Author        string
	Description   string
	SchemaVersion int64
	RawJson       string
	ThemeID       string
}

func (q *Queries) UpdateThemePack(ctx context.Context, arg UpdateThemePackParams) error {
	_, err := q.db.ExecContext(ctx, updateThemePack,
		arg.Name,
		arg.Version,
		arg.Author,
		arg.Description,
		arg.SchemaVersion,
		arg.RawJson,
		arg.ThemeID,
	)
	return err
}
